package frc.robot.commands;

import static edu.wpi.first.units.Units.*;

import java.util.Optional;
import java.util.Set;
import java.util.function.BooleanSupplier;
import java.util.function.DoubleSupplier;
import java.util.function.Supplier;

import com.ctre.phoenix6.SignalLogger;
import com.ctre.phoenix6.Utils;
import com.ctre.phoenix6.swerve.SwerveDrivetrainConstants;
import com.ctre.phoenix6.swerve.SwerveModule.DriveRequestType;
import com.ctre.phoenix6.swerve.SwerveModuleConstants;
import com.ctre.phoenix6.swerve.SwerveRequest;
import com.pathplanner.lib.auto.AutoBuilder;
import com.pathplanner.lib.commands.PathPlannerAuto;
import com.pathplanner.lib.config.PIDConstants;
import com.pathplanner.lib.config.RobotConfig;
import com.pathplanner.lib.controllers.PPHolonomicDriveController;
import com.pathplanner.lib.path.PathConstraints;

import edu.wpi.first.math.Matrix;
import edu.wpi.first.math.VecBuilder;
import edu.wpi.first.math.filter.Debouncer;
import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import edu.wpi.first.math.geometry.Translation2d;
import edu.wpi.first.math.kinematics.ChassisSpeeds;
import edu.wpi.first.math.numbers.N1;
import edu.wpi.first.math.numbers.N3;
import edu.wpi.first.networktables.DoublePublisher;
import edu.wpi.first.networktables.NetworkTableInstance;
import edu.wpi.first.wpilibj.DriverStation;
import edu.wpi.first.wpilibj.DriverStation.Alliance;
import edu.wpi.first.wpilibj.Notifier;
import edu.wpi.first.wpilibj.RobotController;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.Commands;
import edu.wpi.first.wpilibj2.command.Subsystem;
import edu.wpi.first.wpilibj2.command.sysid.SysIdRoutine;
import frc.robot.Constants.FieldConstants;
import frc.robot.Constants.SubsystemConstants.DriveConstants;
import frc.robot.Constants.SubsystemConstants.Vision;
import frc.robot.Constants.TunerConstants.TunerSwerveDrivetrain;
import frc.robot.subsystems.utility.LimelightHelpers;
import frc.robot.util.Tunable;
import frc.robot.subsystems.utility.LimelightHelpers.PoseEstimate;

/**
 * Class that extends the Phoenix 6 SwerveDrivetrain class and implements
 * Subsystem so it can easily be used in command-based projects.
 *
 * Generated by the 2026 Tuner X Swerve Project Generator
 * 
 * https://v6.docs.ctr-electronics.com/en/stable/docs/tuner/tuner-swerve/index.html
 */
public class CommandSwerveDrivetrain extends TunerSwerveDrivetrain implements Subsystem {
    private static final double kSimLoopPeriod = 0.004; // 4 ms
    private Notifier m_simNotifier = null;
    private double m_lastSimTime;

    /* Blue alliance sees forward as 0 degrees (toward red alliance wall) */
    private static final Rotation2d kBlueAlliancePerspectiveRotation = Rotation2d.kZero;
    /* Red alliance sees forward as 180 degrees (toward blue alliance wall) */
    private static final Rotation2d kRedAlliancePerspectiveRotation = Rotation2d.k180deg;
    /* Keep track if we've ever applied the operator perspective before or not */
    private boolean m_hasAppliedOperatorPerspective = false;
    /* Latched true at the first enable after boot. Locks out the MT1 vision auto-seed for
     * the rest of the match (team request 2026-07-21): once enabled, field centering can
     * ONLY come from the driver's MENU press (seedFieldCentric). */
    private boolean m_hasBeenEnabled = false;

    /* Swerve requests to apply during SysId characterization */
    private final SwerveRequest.SysIdSwerveTranslation m_translationCharacterization = new SwerveRequest.SysIdSwerveTranslation();
    private final SwerveRequest.SysIdSwerveSteerGains m_steerCharacterization = new SwerveRequest.SysIdSwerveSteerGains();
    private final SwerveRequest.SysIdSwerveRotation m_rotationCharacterization = new SwerveRequest.SysIdSwerveRotation();

    /* SwerveRequest.ApplyChassisSpeeds */
        SwerveRequest.ApplyRobotSpeeds m_applyRobotSpeeds = new SwerveRequest.ApplyRobotSpeeds();

    /* SysId routine for characterizing translation. This is used to find PID gains for the drive motors. */
    private final SysIdRoutine m_sysIdRoutineTranslation = new SysIdRoutine(
        new SysIdRoutine.Config(
            null,        // Use default ramp rate (1 V/s)
            Volts.of(4), // Reduce dynamic step voltage to 4 V to prevent brownout
            null,        // Use default timeout (10 s)
            // Log state with SignalLogger class
            state -> SignalLogger.writeString("SysIdTranslation_State", state.toString())
        ),
        new SysIdRoutine.Mechanism(
            output -> setControl(m_translationCharacterization.withVolts(output)),
            null,
            this
        )
    );

    /* SysId routine for characterizing steer. This is used to find PID gains for the steer motors. */
    private final SysIdRoutine m_sysIdRoutineSteer = new SysIdRoutine(
        new SysIdRoutine.Config(
            null,        // Use default ramp rate (1 V/s)
            Volts.of(7), // Use dynamic voltage of 7 V
            null,        // Use default timeout (10 s)
            // Log state with SignalLogger class
            state -> SignalLogger.writeString("SysIdSteer_State", state.toString())
        ),
        new SysIdRoutine.Mechanism(
            volts -> setControl(m_steerCharacterization.withVolts(volts)),
            null,
            this
        )
    );

    /*
     * SysId routine for characterizing rotation.
     * This is used to find PID gains for the FieldCentricFacingAngle HeadingController.
     * See the documentation of SwerveRequest.SysIdSwerveRotation for info on importing the log to SysId.
     */
    // private final SysIdRoutine m_sysIdRoutineRotation = new SysIdRoutine(
    //     new SysIdRoutine.Config(
    //         /* This is in radians per second², but SysId only supports "volts per second" */
    //         Volts.of(Math.PI / 6).per(Second),
    //         /* This is in radians per second, but SysId only supports "volts" */
    //         Volts.of(Math.PI),
    //         null, // Use default timeout (10 s)
    //         // Log state with SignalLogger class
    //         state -> SignalLogger.writeString("SysIdRotation_State", state.toString())
    //     ),
    //     new SysIdRoutine.Mechanism(
    //         output -> {
    //             /* output is actually radians per second,    but SysId only supports "volts" */
    //             setControl(m_rotationCharacterization.withRotationalRate(output.in(Volts)));
    //             /* also log the requested output for SysId */
    //             SignalLogger.writeDouble("Rotational_Rate", output.in(Volts));
    //         },
    //         null,
    //         this
    //     )
    // );

    /* The SysId routine to test */
    private SysIdRoutine m_sysIdRoutineToApply = m_sysIdRoutineTranslation;

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not construct
     * the devices themselves. If they need the devices, they can access them through
     * getters in the classes.
     *
     * @param drivetrainConstants   Drivetrain-wide constants for the swerve drive
     * @param modules               Constants for each specific module
     */
    public CommandSwerveDrivetrain(
        SwerveDrivetrainConstants drivetrainConstants,
        SwerveModuleConstants<?, ?, ?>... modules
    ) {
        super(drivetrainConstants, modules);
        if (Utils.isSimulation()) {
            startSimThread();
        }
        configurePathPlanner();
    }

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not construct
     * the devices themselves. If they need the devices, they can access them through
     * getters in the classes.
     *
     * @param drivetrainConstants     Drivetrain-wide constants for the swerve drive
     * @param odometryUpdateFrequency The frequency to run the odometry loop. If
     *                                unspecified or set to 0 Hz, this is 250 Hz on
     *                                CAN FD, and 100 Hz on CAN 2.0.
     * @param modules                 Constants for each specific module
     */
    public CommandSwerveDrivetrain(
        SwerveDrivetrainConstants drivetrainConstants,
        double odometryUpdateFrequency,
        SwerveModuleConstants<?, ?, ?>... modules
    ) {
        super(drivetrainConstants, odometryUpdateFrequency, modules);
        if (Utils.isSimulation()) {
            startSimThread();
        }
        configurePathPlanner();
    }

    /**
     * Constructs a CTRE SwerveDrivetrain using the specified constants.
     * <p>
     * This constructs the underlying hardware devices, so users should not construct
     * the devices themselves. If they need the devices, they can access them through
     * getters in the classes.
     *
     * @param drivetrainConstants       Drivetrain-wide constants for the swerve drive
     * @param odometryUpdateFrequency   The frequency to run the odometry loop. If
     *                                  unspecified or set to 0 Hz, this is 250 Hz on
     *                                  CAN FD, and 100 Hz on CAN 2.0.
     * @param odometryStandardDeviation The standard deviation for odometry calculation
     *                                  in the form [x, y, theta]ᵀ, with units in meters
     *                                  and radians
     * @param visionStandardDeviation   The standard deviation for vision calculation
     *                                  in the form [x, y, theta]ᵀ, with units in meters
     *                                  and radians
     * @param modules                   Constants for each specific module
     */
    public CommandSwerveDrivetrain(
        SwerveDrivetrainConstants drivetrainConstants,
        double odometryUpdateFrequency,
        Matrix<N3, N1> odometryStandardDeviation,
        Matrix<N3, N1> visionStandardDeviation,
        SwerveModuleConstants<?, ?, ?>... modules
    ) {
        super(drivetrainConstants, odometryUpdateFrequency, odometryStandardDeviation, visionStandardDeviation, modules);
        if (Utils.isSimulation()) {
            startSimThread();
        }
        configurePathPlanner();
    }
    /**
     * Configures the PathPlanner AutoBuilder for this drivetrain. This allows you to use PathPlanner's path following features with this drivetrain.
     */

    private void configurePathPlanner(){
        RobotConfig config = null;
            try{
                config = RobotConfig.fromGUISettings();
            } catch (Exception e) {
                // Loud failure: without this config AutoBuilder is never configured and ALL
                // path following silently dies. Surface it on the Driver Station.
                DriverStation.reportError(
                    "PathPlanner RobotConfig failed to load -- autos and path following are DISABLED: "
                        + e.getMessage(), e.getStackTrace());
            }
        if(config != null){
            // Named so the PID panel can show them read-only. NOT live-tunable: PPHolonomicDriveController
            // bakes these in at configure time, so changing one needs a redeploy.
            PIDConstants ppTranslation = new PIDConstants(5.0, 0.0, 0.0); // m/s per m of error; old 0.0001 was effectively open-loop. TODO tune on robot
            PIDConstants ppRotation = new PIDConstants(5.0, 0.0, 0.0);
            Tunable.publishReadOnly("Auto/Translation/kP", ppTranslation.kP);
            Tunable.publishReadOnly("Auto/Rotation/kP", ppRotation.kP);
                  //Configure Auto Builder
            AutoBuilder.configure(
            () -> this.getState().Pose, // Robot pose supplier
            pose -> this.resetPose(pose), // Reset odometry to the path's full start pose (X, Y AND rotation -- seedFieldCentric only set heading and silently dropped X/Y)
            () -> this.getState().Speeds, // ChassisSpeeds supplier. MUST BE ROBOT RELATIVE
            (speeds, feedforwards) -> this.setControl(m_applyRobotSpeeds.withSpeeds(speeds).withWheelForceFeedforwardsX(feedforwards.robotRelativeForcesX()).withWheelForceFeedforwardsY(feedforwards.robotRelativeForcesY())), // Method that will drive the robot given ROBOT RELATIVE ChassisSpeeds. Also optionally outputs individual module feedforwards
            new PPHolonomicDriveController( // PPHolonomicController is the built in path following controller for holonomic drive trains
                    ppTranslation,
                    ppRotation
            ),
            config, // The robot configuration
            () -> {

              // Boolean supplier that controls when the path will be mirrored for the red alliance
              // This will flip the path being followed to the red side of the field.
              // THE ORIGIN WILL REMAIN ON THE BLUE SIDE

              var alliance = DriverStation.getAlliance();
              if (alliance.isPresent()) {
                return alliance.get() == DriverStation.Alliance.Red;
              }
              return false;
            },
            this // Reference to this subsystem to set requirements
            );
        }
    }
    
    /**
     * 
     * Returns a command that runs the specified path from PathPlanner. The path must be located in the "paths" folder in the project directory, and should be created using the PathPlanner tool.
     * @param name
     * @return Auto Command
     */
        public Command getAuton(String name){
            return new PathPlannerAuto(name);
        }

    /**
     * Returns a command that applies the specified control request to this swerve drivetrain.
     *
     * @param request Function returning the request to apply
     * @return Command to run
     */
    public Command applyRequest(Supplier<SwerveRequest> request) {
        return run(() -> this.setControl(request.get()));
    }

    /**
     * Runs the SysId Quasistatic test in the given direction for the routine
     * specified by {@link #m_sysIdRoutineToApply}.
     *
     * @param direction Direction of the SysId Quasistatic test
     * @return Command to run
     */
    public Command sysIdQuasistatic(SysIdRoutine.Direction direction) {
        return m_sysIdRoutineToApply.quasistatic(direction);
    }

    /**
     * Runs the SysId Dynamic test in the given direction for the routine
     * specified by {@link #m_sysIdRoutineToApply}.
     *
     * @param direction Direction of the SysId Dynamic test
     * @return Command to run
     */
    public Command sysIdDynamic(SysIdRoutine.Direction direction) {
        return m_sysIdRoutineToApply.dynamic(direction);
    }

    @Override
    public void periodic() {
        /*
         * Periodically try to apply the operator perspective.
         * If we haven't applied the operator perspective before, then we should apply it regardless of DS state.
         * This allows us to correct the perspective in case the robot code restarts mid-match.
         * Otherwise, only check and apply the operator perspective if the DS is disabled.
         * This ensures driving behavior doesn't change until an explicit disable event occurs during testing.
         */
        if (!m_hasAppliedOperatorPerspective || DriverStation.isDisabled()) {
            DriverStation.getAlliance().ifPresent(allianceColor -> {
                setOperatorPerspectiveForward(
                    allianceColor == Alliance.Red
                        ? kRedAlliancePerspectiveRotation
                        : kBlueAlliancePerspectiveRotation
                );
                m_hasAppliedOperatorPerspective = true;
            });
        }
        // First enable after boot latches the vision boot-seed off for good (see field doc).
        if (DriverStation.isEnabled()) {
            m_hasBeenEnabled = true;
        }
        // AprilTag pose correction: MT1 boot-seed + MegaTag2 X/Y fusion (team request
        // 2026-07-17). PREREQUISITE: Limelight camera mount pose set in its web UI --
        // see Vision.ENABLE_MEGATAG2_POSE.
        if (Vision.ENABLE_MEGATAG2_POSE) {
            updateVisionPose();
        }
    }

    // "Tags currently correcting the pose" for the driver-companion field map's vision
    // badge: 0 = odometry only. Lives in the same NT table as Pose/robotPose (Telemetry).
    private final DoublePublisher visionTagCountPub = NetworkTableInstance.getDefault()
        .getTable("Pose").getDoubleTopic("visionTagCount").publish();

    // Heading-servo gains, live-tunable from the driver-companion PID panel. setPID is called
    // fresh every time one of the aim/align requests is built, so reading these needs no
    // re-apply gating. Constant values when TUNING_MODE is off.
    private final Tunable headingKp = new Tunable("Drive/Heading/kP", DriveConstants.HEADING_kP);
    private final Tunable headingKi = new Tunable("Drive/Heading/kI", DriveConstants.HEADING_kI);
    private final Tunable headingKd = new Tunable("Drive/Heading/kD", DriveConstants.HEADING_kD);

    /**
     * AprilTag pose correction, two layers (both BLUE-origin -- PathPlanner and this
     * drivetrain keep the origin on the blue side for both alliances):
     * 1. BOOT-SEED (MegaTag1): ONLY until the robot is first enabled after boot, adopt the
     *    full tag pose whenever it disagrees with odometry (pre-match auto re-zero -- the
     *    robot is sitting still). The in-match auto re-seed was REMOVED 2026-07-21 by team
     *    request: once the match starts, field centering comes ONLY from the driver's MENU
     *    press -- a mid-match heading skew (collision, gyro drift) stays until the driver
     *    squares the robot up and presses MENU.
     * 2. FUSION (MegaTag2): continuous X/Y correction; yaw std dev is huge so the Pigeon
     *    always owns heading.
     * Safe to call with no Limelight connected.
     */
    private void updateVisionPose() {
        // Feed the Limelight our gyro yaw (deg, blue-origin) -- required for MegaTag2.
        LimelightHelpers.SetRobotOrientation(Vision.CAM_LIMELIGHT,
            this.getState().Pose.getRotation().getDegrees(), 0, 0, 0, 0, 0);
        LimelightHelpers.SetIMUMode(Vision.CAM_LIMELIGHT,
            (DriverStation.isAutonomous()) ? 1 : 4
        );
            // 1 -> EXTERNAL_SEED : Seed internal IMU
            // 4 -> INTERNAL_EXTERNAL_ASSIST : Use internal IMU + MT1

        // ---- Layer 1: MT1 boot-seed (latched off at the first enable) ----
        if (!m_hasBeenEnabled) {
            PoseEstimate mt1 = LimelightHelpers.getBotPoseEstimate_wpiBlue(Vision.CAM_LIMELIGHT);
            if (mt1 != null && mt1.tagCount >= 1
                    && mt1.avgTagDist <= Vision.VISION_SEED_MAX_TAG_DIST_METERS
                    && isInsideField(mt1.pose)) {
                Pose2d current = this.getState().Pose;
                double posErrMeters = mt1.pose.getTranslation().getDistance(current.getTranslation());
                double yawErrDeg = Math.abs(mt1.pose.getRotation().minus(current.getRotation()).getDegrees());
                if (posErrMeters > Vision.VISION_SEED_POS_TOL_METERS
                        || yawErrDeg > Vision.VISION_SEED_YAW_TOL_DEG) {
                    this.resetPose(mt1.pose);
                    visionTagCountPub.set(mt1.tagCount);
                    return; // pose buffer just reset -- skip fusing stale MT2 this loop
                }
            }
        }

        // ---- Layer 2: MegaTag2 X/Y fusion ----
        PoseEstimate mt2 = LimelightHelpers.getBotPoseEstimate_wpiBlue_MegaTag2(Vision.CAM_LIMELIGHT);
        if (mt2 == null || mt2.tagCount == 0) {
            visionTagCountPub.set(0); // no Limelight data / no tags in view
            return;
        }
        if (Math.abs(this.getPigeon2().getAngularVelocityZDevice().getValueAsDouble()) > 360) {
            visionTagCountPub.set(0); // spinning too fast for a trustworthy MegaTag2 solve
            return;
        }
        // Trust MegaTag2 X/Y, never its yaw (huge theta std dev) -- the Pigeon owns heading.
        this.addVisionMeasurement(mt2.pose, mt2.timestampSeconds, VecBuilder.fill(0.7, 0.7, 9999999));
        visionTagCountPub.set(mt2.tagCount);
    }

    /** Rejects botpose solves that land outside the field -- a garbage solve can't seed. */
    private static boolean isInsideField(Pose2d pose) {
        return pose.getX() >= 0 && pose.getX() <= FieldConstants.FIELD_LENGTH_METERS
            && pose.getY() >= 0 && pose.getY() <= FieldConstants.FIELD_WIDTH_METERS;
    }

    private void startSimThread() {
        m_lastSimTime = Utils.getCurrentTimeSeconds();

        /* Run simulation at a faster rate so PID gains behave more reasonably */
        m_simNotifier = new Notifier(() -> {
            final double currentTime = Utils.getCurrentTimeSeconds();
            double deltaTime = currentTime - m_lastSimTime;
            m_lastSimTime = currentTime;

            /* use the measured time delta, get battery voltage from WPILib */
            updateSimState(deltaTime, RobotController.getBatteryVoltage());
        });
        m_simNotifier.startPeriodic(kSimLoopPeriod);
    }

    /**
     * Adds a vision measurement to the Kalman Filter. This will correct the odometry pose estimate
     * while still accounting for measurement noise.
     *
     * @param visionRobotPoseMeters The pose of the robot as measured by the vision camera.
     * @param timestampSeconds The timestamp of the vision measurement in seconds.
     */
    @Override
    public void addVisionMeasurement(Pose2d visionRobotPoseMeters, double timestampSeconds) {
        super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds));
    }

    /**
     * Adds a vision measurement to the Kalman Filter. This will correct the odometry pose estimate
     * while still accounting for measurement noise.
     * <p>
     * Note that the vision measurement standard deviations passed into this method
     * will continue to apply to future measurements until a subsequent call to
     * {@link #setVisionMeasurementStdDevs(Matrix)} or this method.
     *
     * @param visionRobotPoseMeters The pose of the robot as measured by the vision camera.
     * @param timestampSeconds The timestamp of the vision measurement in seconds.
     * @param visionMeasurementStdDevs Standard deviations of the vision pose measurement
     *     in the form [x, y, theta]ᵀ, with units in meters and radians.
     */
    @Override
    public void addVisionMeasurement(
        Pose2d visionRobotPoseMeters,
        double timestampSeconds,
        Matrix<N3, N1> visionMeasurementStdDevs
    ) {
        super.addVisionMeasurement(visionRobotPoseMeters, Utils.fpgaToCurrentTime(timestampSeconds), visionMeasurementStdDevs);
    }

    /**
     * Return the pose at a given timestamp, if the buffer is not empty.
     *
     * @param timestampSeconds The timestamp of the pose in seconds.
     * @return The pose at the given timestamp (or Optional.empty() if the buffer is empty).
     */
    @Override
    public Optional<Pose2d> samplePoseAt(double timestampSeconds) {
        return super.samplePoseAt(Utils.fpgaToCurrentTime(timestampSeconds));
    }

    public Command rotateToAngle(double targetAngleDegrees){
        return rotateToAngle(() -> targetAngleDegrees);
    }

    /**
     * Supplier overload so the target can be a LIVE value (e.g. a vision bearing that updates
     * every loop). A plain double is frozen at binding-construction time -- binding
     * rotateToAngle(shooter.getDegreesToAlignToTarget()) would rotate to whatever the value was
     * at boot (0 deg) forever; bind rotateToAngle(shooter::getDegreesToAlignToTarget) instead.
     */
    public Command rotateToAngle(DoubleSupplier targetAngleDegrees){
        var request = new SwerveRequest.FieldCentricFacingAngle();
        // The HeadingController gains default to 0 -- without this the request outputs zero
        // rotation and the command would hold the drivetrain forever. Radians in, rad/s out.
        request.HeadingController.setPID(
            headingKp.get(), headingKi.get(), headingKd.get()); // live-tunable, see Tunable
        request.HeadingController.enableContinuousInput(-Math.PI, Math.PI); // take the short way around
        // Cap the commanded spin (P-only at 5 rad/s per rad could otherwise demand ~15 rad/s).
        request.MaxAbsRotationalRate = 1.5 * Math.PI; // rad/s. TODO tune on robot
        // Targets here are computed from the BLUE-ORIGIN pose (pose heading + delta), but the
        // request DEFAULTS to OperatorPerspective, which re-rotates TargetDirection 180 deg on
        // red alliance -- the servo would chase the wrong heading while the .until() tolerance
        // (blue-frame) could never latch. Fixed 2026-07-17.
        request.ForwardPerspective = SwerveRequest.ForwardPerspectiveValue.BlueAlliance;

        // The command must END when on target (or on the timeout backstop) so the drivetrain
        // returns to the driver's default drive command -- chaining an Idle request here would
        // hold the drivetrain forever and lock the driver out.
        return this.applyRequest(() ->
            request.withTargetDirection(
                Rotation2d.fromDegrees(targetAngleDegrees.getAsDouble())
            )
        ).until(() ->
            // Rotation2d.minus wraps, so 179 deg vs -179 deg reads as 2 deg apart, not 358.
            Math.abs(
                this.getState().Pose.getRotation()
                    .minus(Rotation2d.fromDegrees(targetAngleDegrees.getAsDouble())).getDegrees()
            ) < 2 // deg. P-only control may hold a small steady-state error; 1 deg could never latch
        ).withTimeout(2.0); // s -- backstop so a stalled align can never hang the drivetrain. TODO tune
    }

    /**
     * SEARCH-ALIGN (A / DPAD-UP, hold): while no usable tag is in view, rotate in place
     * slowly (translation stays zero) so the Limelight sweeps the field; the moment seesTag
     * reports a scoring tag of OUR alliance, face it -- targetHeadingDegrees is re-sampled
     * EVERY loop, so the aim tracks the live vision bearing. Deliberately never self-ends
     * (no until/withTimeout): this is bound whileTrue, so the driver's hold IS the timeout
     * and release returns the drivetrain to the default drive command.
     */
    public Command searchAndAlignCommand(BooleanSupplier seesTag, DoubleSupplier targetHeadingDegrees){
        var searchRequest = new SwerveRequest.FieldCentric(); // velocities default 0 -- rotate in place
        var faceRequest = new SwerveRequest.FieldCentricFacingAngle();
        // Same heading-servo setup as rotateToAngle: the HeadingController gains default to 0
        // (zero rotation output without this), continuous input takes the short way around,
        // and the rate cap tames P-only spikes. Radians in, rad/s out.
        faceRequest.HeadingController.setPID(
            headingKp.get(), headingKi.get(), headingKd.get()); // live-tunable, see Tunable
        faceRequest.HeadingController.enableContinuousInput(-Math.PI, Math.PI);
        faceRequest.MaxAbsRotationalRate = 1.5 * Math.PI; // rad/s. TODO tune on robot
        // Blue-origin targets (pose heading + camera bearing) -- see rotateToAngle: the
        // OperatorPerspective default would re-rotate them 180 deg on red alliance.
        faceRequest.ForwardPerspective = SwerveRequest.ForwardPerspectiveValue.BlueAlliance;

        return this.applyRequest(() ->
            seesTag.getAsBoolean()
                ? faceRequest.withTargetDirection(
                    Rotation2d.fromDegrees(targetHeadingDegrees.getAsDouble()))
                : searchRequest.withRotationalRate(
                    FieldConstants.SEARCH_ROTATE_RATE_ROT_PER_SEC * 2.0 * Math.PI) // rot/s -> rad/s, CCW
        );
    }

    // (driveWithAimLockCommand DELETED 2026-07-21: unused since the 07-17 RT redesign to
    // aim-then-freeze. If strafe-while-aiming ever comes back, restore it from git history
    // at commit 1a88475 or earlier -- it handled the operator->blue frame rotation.)

    /**
     * AIM-then-stop for the precision shot (team request 2026-07-17: "auto-aim, THEN disable
     * drive"). Rotate IN PLACE (translation 0) toward the live blue-origin {@code targetHeadingDeg}
     * and END the instant {@code aimed} reports the robot is lined up on a REAL target. Differs
     * from {@link #rotateToAngle}: it ends on the SHOOTER's own aim gate (not a fixed 2 deg) and
     * has NO timeout -- with no target {@code aimed} never latches, so it just holds heading rather
     * than ending early and letting a never-aimed shot fire. The caller sequences a freeze (Idle)
     * + feed AFTER this, so the drivetrain is disabled and fuel is fed only once the aim is made.
     */
    public Command aimUntilAligned(DoubleSupplier targetHeadingDeg, BooleanSupplier aimed) {
        var request = new SwerveRequest.FieldCentricFacingAngle();
        // Same heading servo as rotateToAngle / driveWithAimLock. Radians in, rad/s out.
        request.HeadingController.setPID(
            headingKp.get(), headingKi.get(), headingKd.get()); // live-tunable, see Tunable
        request.HeadingController.enableContinuousInput(-Math.PI, Math.PI);
        request.MaxAbsRotationalRate = 1.5 * Math.PI; // rad/s
        // Blue-origin bearing (from pose) -- OperatorPerspective default would re-rotate it 180 on red.
        request.ForwardPerspective = SwerveRequest.ForwardPerspectiveValue.BlueAlliance;
        return this.applyRequest(() ->
                request.withTargetDirection(Rotation2d.fromDegrees(targetHeadingDeg.getAsDouble())))
            .until(aimed);
    }

    /**
     * DPAD-LEFT/RIGHT: rotate exactly deltaDegrees (CCW positive, per WPILib convention)
     * from wherever the robot points when the command is SCHEDULED -- deferred, because a
     * heading read at binding-construction time would snapshot the boot heading forever.
     * Delegates to rotateToAngle, keeping its 2 deg tolerance and 2 s timeout so the
     * command self-ends and hands the drivetrain back to the driver.
     */
    public Command rotateBy(double deltaDegrees){
        return Commands.defer(
            () -> rotateToAngle(this.getState().Pose.getRotation().getDegrees() + deltaDegrees),
            Set.of(this));
    }

    // ---- Simple drive-forward autonomous with stall abort ----
    // Stall = a wheel or the whole robot jammed against something. We watch every drive AND steer
    // motor's MEASURED stator current (getStatorCurrent, not commanded output) and abort the whole
    // drive the moment any of them pins high longer than the debounce -- so the robot never keeps
    // grinding into a jam or a wall. Thresholds sit below each motor's configured stator limit
    // (drive slip = 120 A, steer = 40 A, see TunerConstants) but well above normal cruise draw.
    // TODO tune all three on the robot.
    private static final double kAutoDriveStallAmps = 90.0;   // A, per drive Kraken X60
    private static final double kAutoSteerStallAmps = 35.0;   // A, per steer Kraken X44
    private static final double kAutoStallDebounceSec = 0.3;  // s any motor must stay stalled to abort

    /** True if ANY module's drive or steer motor is drawing stall-level stator current right now. */
    private boolean anyDriveMotorStalled() {
        for (var module : getModules()) {
            double driveAmps = Math.abs(module.getDriveMotor().getStatorCurrent().getValueAsDouble());
            double steerAmps = Math.abs(module.getSteerMotor().getStatorCurrent().getValueAsDouble());
            if (driveAmps >= kAutoDriveStallAmps || steerAmps >= kAutoSteerStallAmps) {
                return true;
            }
        }
        return false;
    }

    /**
     * Basic autonomous: drive ROBOT-relative straight forward at a fixed speed until the robot has
     * traveled {@code meters} (measured by odometry) OR any drive/steer motor stalls. On either end
     * the wheels lock in an X (SwerveDriveBrake) and the command finishes, handing the drivetrain
     * back to the default command (which holds zero velocity). Deferred so the start pose and the
     * stall debouncer are fresh every time it's scheduled.
     *
     * @param meters          distance to travel forward (m)
     * @param metersPerSecond forward speed (m/s), closed-loop velocity
     */
    public Command driveForwardAuto(double meters, double metersPerSecond) {
        return Commands.defer(() -> {
            Translation2d start = this.getState().Pose.getTranslation();
            Debouncer stallDebounce = new Debouncer(kAutoStallDebounceSec, Debouncer.DebounceType.kRising);
            var driveForward = new SwerveRequest.RobotCentric()
                .withDriveRequestType(DriveRequestType.Velocity); // closed-loop velocity
            var lock = new SwerveRequest.SwerveDriveBrake();
            return this.applyRequest(() -> driveForward
                        .withVelocityX(metersPerSecond)
                        .withVelocityY(0)
                        .withRotationalRate(0))
                    .until(() ->
                        start.getDistance(this.getState().Pose.getTranslation()) >= meters
                        || stallDebounce.calculate(anyDriveMotorStalled()))
                    // One-shot X-lock so the command ENDS (default command then holds 0) -- a
                    // run-forever brake leg would keep the drivetrain and lock the driver out.
                    .andThen(this.runOnce(() -> this.setControl(lock)));
        }, Set.of(this));
    }

    public Command driveToPose(Pose2d targetPose){
        PathConstraints constraints = new PathConstraints(
            Vision.PP_MAX_VELOCITY, 
            Vision.PP_MAX_ACCELERATION, 
            Vision.PP_MAX_ANGULAR_VELOCITY, 
            Vision.PP_MAX_ANGULAR_ACCELERATION
        );
        Command pathfindingCommand = AutoBuilder.pathfindToPose(targetPose, constraints, 0.0);
        return pathfindingCommand;
    }

    public Command driveToPose(Translation2d targetTranslation, Translation2d velocityTranslation){
        // Deferred so the CURRENT pose is read when the command is scheduled, not when the
        // binding is constructed at boot.
        return Commands.defer(() -> {
            double velocityMag = velocityTranslation.getNorm();
            if(velocityMag < 0.001){
                return Commands.none();
            }

            // Distance from where the robot IS to the target. The old code used
            // targetTranslation.getNorm() -- the target's distance from the FIELD ORIGIN (0,0),
            // which is unrelated to how far the robot actually has to travel.
            double distance = targetTranslation.minus(this.getState().Pose.getTranslation()).getNorm();
            double time = distance / velocityMag;

            var idle = new SwerveRequest.Idle();

            return this.applyRequest(() ->
                m_applyRobotSpeeds.withSpeeds(
                    ChassisSpeeds.fromFieldRelativeSpeeds(
                        velocityTranslation.getX(),
                        velocityTranslation.getY(),
                        0,
                        this.getState().Pose.getRotation()
                    )
                )
            ).withTimeout(time)
            // One-shot stop so the command ENDS and the driver's default command resumes -- a
            // run-forever applyRequest(Idle) leg would hold the drivetrain and lock the driver out.
            .andThen(this.runOnce(() -> this.setControl(idle)));
        }, Set.of(this));
    }
}
