package frc.robot.Constants;

import static edu.wpi.first.units.Units.*;

import com.ctre.phoenix6.CANBus;
import com.ctre.phoenix6.configs.*;
import com.ctre.phoenix6.hardware.*;
import com.ctre.phoenix6.signals.*;
import com.ctre.phoenix6.swerve.*;
import com.ctre.phoenix6.swerve.SwerveModuleConstants.*;

import edu.wpi.first.math.Matrix;
import edu.wpi.first.math.VecBuilder;
import edu.wpi.first.math.numbers.N1;
import edu.wpi.first.math.numbers.N3;
import edu.wpi.first.units.measure.*;

import frc.robot.commands.CommandSwerveDrivetrain;

// Generated by the 2026 Tuner X Swerve Project Generator
// https://v6.docs.ctr-electronics.com/en/stable/docs/tuner/tuner-swerve/index.html
public class TunerConstants {
    // Both sets of gains need to be tuned to your individual robot.

    // The steer motor uses any SwerveModule.SteerRequestType control request with the
    // output type specified by SwerveModuleConstants.SteerMotorClosedLoopOutput
    private static final Slot0Configs steerGains = new Slot0Configs()
        // TUNING LOG (on-robot 2026-07-08): kP=100/kD=0.5 (CTRE template values) was violently
        // unstable here -- those assume Pro FusedCANcoder feedback; with our unlicensed
        // RemoteCANcoder the feedback is slower/delayed and kP=100 chattered ("locked up
        // constantly"). Telemetry capture (2026-07-08, on blocks): steady-state tracking is
        // ~1.3 deg median error; fast stick whips put modules 25-90 deg behind target and
        // cosine compensation cuts drive -- the perceived "locking". That transient is mostly
        // physics (azimuth slew time) + Remote feedback latency; Pro license (FusedCANcoder)
        // is the real fix. kP=50 = highest tested-stable value; do not jump to 100 unlicensed.
        .withKP(50).withKI(0).withKD(0)
        .withKS(0).withKV(0)
        .withStaticFeedforwardSign(StaticFeedforwardSignValue.UseClosedLoopSign);
    // When using closed-loop control, the drive motor uses the control
    // output type specified by SwerveModuleConstants.DriveMotorClosedLoopOutput
    private static final Slot0Configs driveGains = new Slot0Configs()
        .withKP(0.01).withKI(0).withKD(0)
        .withKS(0).withKV(0.1165);

    // The closed-loop output type to use for the steer motors;
    // This affects the PID/FF gains for the steer motors
    private static final ClosedLoopOutputType kSteerClosedLoopOutput = ClosedLoopOutputType.Voltage;
    // The closed-loop output type to use for the drive motors;
    // This affects the PID/FF gains for the drive motors
    private static final ClosedLoopOutputType kDriveClosedLoopOutput = ClosedLoopOutputType.Voltage;

    // The type of motor used for the drive motor
    private static final DriveMotorArrangement kDriveMotorType = DriveMotorArrangement.TalonFX_Integrated;
    // The type of motor used for the drive motor
    private static final SteerMotorArrangement kSteerMotorType = SteerMotorArrangement.TalonFX_Integrated;

    // The remote sensor feedback type to use for the steer motors.
    // RemoteCANcoder, NOT FusedCANcoder: our Krakens are UNLICENSED (confirmed on-robot 2026-07-08 --
    // netconsole showed "Talon ID 1/4/7/10 failed config: UsingProFeatureOnUnlicensedDevice" at boot,
    // i.e. the steer configs were being rejected). Fused is Phoenix Pro only; switch back if the team
    // ever buys a season pass / Pro license.
    private static final SteerFeedbackType kSteerFeedbackType = SteerFeedbackType.RemoteCANcoder;

    // The stator current at which the wheels start to slip;
    // This needs to be tuned to your individual robot
    private static final Current kSlipCurrent = Amps.of(120);

    // Initial configs for the drive and steer motors and the azimuth encoder; these cannot be null.
    // Some configs will be overwritten; check the `with*InitialConfigs()` API documentation.
    private static final TalonFXConfiguration driveInitialConfigs = new TalonFXConfiguration()
        // Brake the drive motors so the robot decelerates and holds when the stick is released /
        // on disable, instead of coasting on its own momentum (TalonFX default is Coast).
        .withMotorOutput(new MotorOutputConfigs().withNeutralMode(NeutralModeValue.Brake))
        // Supply-current cap = brownout protection for the 4 drive Krakens (draw multiplies x4).
        // Backed down 60 -> 45 A per this comment's own guidance (2026-07-12): NT captures
        // measured drive accel/turn spikes summing to 177 A supply, dipping the battery to
        // 7.0-7.4 V (companion-app BROWNOUT RISK events). 45 A x4 caps the drivetrain burst
        // at ~135 A. NOTE: the battery that session RESTED at 11.5 V (discharged/tired) and
        // sagged ~4 V at 84-130 A -- current limits alone cannot save a weak battery; charge/
        // load-test/swap it and check main-power connections before blaming these numbers.
        // The stator/traction limit comes from kSlipCurrent, which the swerve factory copies
        // into StatorCurrentLimit. If accel feels soft WITH a fresh battery, raise toward 60;
        // hardware sheet cap is 70 -- do not exceed.
        .withCurrentLimits(new CurrentLimitsConfigs()
            .withSupplyCurrentLimit(Amps.of(45))
            // Burst-then-fall-back: 45 A is allowed for accelerations, but sustained draw
            // (pushing matches, stalls) drops to 30 A after 0.5 s -- our battery-efficiency
            // mechanism (tightened from 60/40/1.0 after the measured 2026-07-12 dips).
            .withSupplyCurrentLowerLimit(Amps.of(30))
            .withSupplyCurrentLowerTime(Seconds.of(0.5))
            .withSupplyCurrentLimitEnable(true));
    private static final TalonFXConfiguration steerInitialConfigs = new TalonFXConfiguration()
        .withCurrentLimits(
            new CurrentLimitsConfigs()
                // Steady-state azimuth torque is small, but fast whole-module swings need a burst.
                // The conservative-start 40/20 caps starved the steer motors during quick rotation /
                // direction reversals (modules visibly locked mid-swing, on-robot test 2026-07-08).
                // 60/40 = Hardware-Data-Sheet sec.7 tuned-up ceiling for the steer X44s, and matches
                // the Tuner X project's own 60 A stator value.
                .withStatorCurrentLimit(Amps.of(60))
                .withStatorCurrentLimitEnable(true)
                .withSupplyCurrentLimit(Amps.of(40))
                .withSupplyCurrentLimitEnable(true)
        )
        // Brake so the wheels hold their commanded steer angle instead of coasting.
        .withMotorOutput(new MotorOutputConfigs().withNeutralMode(NeutralModeValue.Brake));
    private static final CANcoderConfiguration encoderInitialConfigs = new CANcoderConfiguration();
    // Configs for the Pigeon 2; leave this null to skip applying Pigeon 2 configs
    private static final Pigeon2Configuration pigeonConfigs = null;

    // CAN bus that the devices are located on;
    // All swerve devices must share the same CAN bus
    public static final CANBus kCANBus = new CANBus("", "./logs/example.hoot");

    // Free speed (m/s) at 12 V applied output. 4.76 = the Tuner X-measured value from
    // tuner-project.json (issue register #19); the old 4.93 was theoretical and unreachable,
    // so full-stick made the drive velocity loop saturate at 12 V chasing a speed it could
    // never hit -- burning current for zero extra speed and skewing odometry scale by ~3.5%.
    // TODO confirm with an on-ground measured-distance run.
    public static final LinearVelocity kSpeedAt12Volts = MetersPerSecond.of(4.76);

    // Every 1 rotation of the azimuth results in kCoupleRatio drive motor turns;
    // This may need to be tuned to your individual robot
    private static final double kCoupleRatio = 5.4;

    private static final double kDriveGearRatio = 6.48;
    private static final double kSteerGearRatio = 12.1;
    private static final Distance kWheelRadius = Inches.of(2);

    // ROBOT FRONT REDEFINED = SHOOTER SIDE (2026-07-10, team request). The Tuner X project
    // was generated with the opposite side as front, so the chassis frame is rotated 180 deg
    // here: module labels swapped diagonally (FL<->BR, FR<->BL, each keeping its own
    // motor/encoder IDs and steer/encoder inversions), every CANcoder offset shifted by
    // exactly +/-0.5 rot, and the left/right drive inversions swapped. If you REGENERATE
    // with Tuner X, its output restores the old front -- reapply this transform (or set the
    // correct front in the generator).
    private static final boolean kInvertLeftSide = true;
    private static final boolean kInvertRightSide = false;
 
    private static final int kPigeonId = 23;

    // These are only used for simulation
    private static final MomentOfInertia kSteerInertia = KilogramSquareMeters.of(0.01);
    private static final MomentOfInertia kDriveInertia = KilogramSquareMeters.of(0.01);
    // Simulated voltage necessary to overcome friction
    private static final Voltage kSteerFrictionVoltage = Volts.of(0.2);
    private static final Voltage kDriveFrictionVoltage = Volts.of(0.2);

    public static final SwerveDrivetrainConstants DrivetrainConstants = new SwerveDrivetrainConstants()
            .withCANBusName(kCANBus.getName())
            .withPigeon2Id(kPigeonId)
            .withPigeon2Configs(pigeonConfigs);

    private static final SwerveModuleConstantsFactory<TalonFXConfiguration, TalonFXConfiguration, CANcoderConfiguration> ConstantCreator =
        new SwerveModuleConstantsFactory<TalonFXConfiguration, TalonFXConfiguration, CANcoderConfiguration>()
            .withDriveMotorGearRatio(kDriveGearRatio)
            .withSteerMotorGearRatio(kSteerGearRatio)
            .withCouplingGearRatio(kCoupleRatio)
            .withWheelRadius(kWheelRadius)
            .withSteerMotorGains(steerGains)
            .withDriveMotorGains(driveGains)
            .withSteerMotorClosedLoopOutput(kSteerClosedLoopOutput)
            .withDriveMotorClosedLoopOutput(kDriveClosedLoopOutput)
            .withSlipCurrent(kSlipCurrent)
            .withSpeedAt12Volts(kSpeedAt12Volts)
            .withDriveMotorType(kDriveMotorType)
            .withSteerMotorType(kSteerMotorType)
            .withFeedbackSource(kSteerFeedbackType)
            .withDriveMotorInitialConfigs(driveInitialConfigs)
            .withSteerMotorInitialConfigs(steerInitialConfigs)
            .withEncoderInitialConfigs(encoderInitialConfigs)
            .withSteerInertia(kSteerInertia)
            .withDriveInertia(kDriveInertia)
            .withSteerFrictionVoltage(kSteerFrictionVoltage)
            .withDriveFrictionVoltage(kDriveFrictionVoltage);


    // Front Left (physically the pre-flip Back Right hardware)
    private static final int kFrontLeftDriveMotorId = 8;
    private static final int kFrontLeftSteerMotorId = 7;
    private static final int kFrontLeftEncoderId = 9;
    private static final Angle kFrontLeftEncoderOffset = Rotations.of(0.2099609375); // -0.2900390625 + 0.5
    private static final boolean kFrontLeftSteerMotorInverted = true;
    private static final boolean kFrontLeftEncoderInverted = false;

    private static final Distance kFrontLeftXPos = Inches.of(13.375);
    private static final Distance kFrontLeftYPos = Inches.of(8.375);

    // Front Right (physically the pre-flip Back Left hardware)
    private static final int kFrontRightDriveMotorId = 2;
    private static final int kFrontRightSteerMotorId = 1;
    private static final int kFrontRightEncoderId = 3;
    private static final Angle kFrontRightEncoderOffset = Rotations.of(-0.149169921875); // 0.350830078125 - 0.5
    private static final boolean kFrontRightSteerMotorInverted = true;
    private static final boolean kFrontRightEncoderInverted = false;

    private static final Distance kFrontRightXPos = Inches.of(13.375);
    private static final Distance kFrontRightYPos = Inches.of(-8.375);

    // Back Left (physically the pre-flip Front Right hardware)
    private static final int kBackLeftDriveMotorId = 5;
    private static final int kBackLeftSteerMotorId = 4;
    private static final int kBackLeftEncoderId = 6;
    private static final Angle kBackLeftEncoderOffset = Rotations.of(-0.0458984375); // 0.4541015625 - 0.5
    private static final boolean kBackLeftSteerMotorInverted = true;
    private static final boolean kBackLeftEncoderInverted = false;

    private static final Distance kBackLeftXPos = Inches.of(-13.375);
    private static final Distance kBackLeftYPos = Inches.of(8.375);

    // Back Right (physically the pre-flip Front Left hardware)
    private static final int kBackRightDriveMotorId = 11;
    private static final int kBackRightSteerMotorId = 10;
    private static final int kBackRightEncoderId = 12;
    private static final Angle kBackRightEncoderOffset = Rotations.of(0.306640625); // -0.193359375 + 0.5
    private static final boolean kBackRightSteerMotorInverted = true;
    private static final boolean kBackRightEncoderInverted = false;

    private static final Distance kBackRightXPos = Inches.of(-13.375);
    private static final Distance kBackRightYPos = Inches.of(-8.375);


    public static final SwerveModuleConstants<TalonFXConfiguration, TalonFXConfiguration, CANcoderConfiguration> FrontLeft =
        ConstantCreator.createModuleConstants(
            kFrontLeftSteerMotorId, kFrontLeftDriveMotorId, kFrontLeftEncoderId, kFrontLeftEncoderOffset,
            kFrontLeftXPos, kFrontLeftYPos, kInvertLeftSide, kFrontLeftSteerMotorInverted, kFrontLeftEncoderInverted
        );
    public static final SwerveModuleConstants<TalonFXConfiguration, TalonFXConfiguration, CANcoderConfiguration> FrontRight =
        ConstantCreator.createModuleConstants(
            kFrontRightSteerMotorId, kFrontRightDriveMotorId, kFrontRightEncoderId, kFrontRightEncoderOffset,
            kFrontRightXPos, kFrontRightYPos, kInvertRightSide, kFrontRightSteerMotorInverted, kFrontRightEncoderInverted
        );
    public static final SwerveModuleConstants<TalonFXConfiguration, TalonFXConfiguration, CANcoderConfiguration> BackLeft =
        ConstantCreator.createModuleConstants(
            kBackLeftSteerMotorId, kBackLeftDriveMotorId, kBackLeftEncoderId, kBackLeftEncoderOffset,
            kBackLeftXPos, kBackLeftYPos, kInvertLeftSide, kBackLeftSteerMotorInverted, kBackLeftEncoderInverted
        );
    public static final SwerveModuleConstants<TalonFXConfiguration, TalonFXConfiguration, CANcoderConfiguration> BackRight =
        ConstantCreator.createModuleConstants(
            kBackRightSteerMotorId, kBackRightDriveMotorId, kBackRightEncoderId, kBackRightEncoderOffset,
            kBackRightXPos, kBackRightYPos, kInvertRightSide, kBackRightSteerMotorInverted, kBackRightEncoderInverted
        );

    /**
     * Creates a CommandSwerveDrivetrain instance.
     * This should only be called once in your robot program,.
     */
    public static CommandSwerveDrivetrain createDrivetrain() {
        return new CommandSwerveDrivetrain(
            DrivetrainConstants,
            100, 
            VecBuilder.fill(0.05,0.05, 0.02), 
            VecBuilder.fill(0.7, 0.7, 1.0), 
            FrontLeft, FrontRight, BackLeft, BackRight
        );
    }


    /**
     * Swerve Drive class utilizing CTR Electronics' Phoenix 6 API with the selected device types.
     */
    public static class TunerSwerveDrivetrain extends SwerveDrivetrain<TalonFX, TalonFX, CANcoder> {
        /**
         * Constructs a CTRE SwerveDrivetrain using the specified constants.
         * <p>
         * This constructs the underlying hardware devices, so users should not construct
         * the devices themselves. If they need the devices, they can access them through
         * getters in the classes.
         *
         * @param drivetrainConstants   Drivetrain-wide constants for the swerve drive
         * @param modules               Constants for each specific module
         */
        public TunerSwerveDrivetrain(
            SwerveDrivetrainConstants drivetrainConstants,
            SwerveModuleConstants<?, ?, ?>... modules
        ) {
            super(
                TalonFX::new, TalonFX::new, CANcoder::new,
                drivetrainConstants, modules
            );
        }

        /**
         * Constructs a CTRE SwerveDrivetrain using the specified constants.
         * <p>
         * This constructs the underlying hardware devices, so users should not construct
         * the devices themselves. If they need the devices, they can access them through
         * getters in the classes.
         *
         * @param drivetrainConstants     Drivetrain-wide constants for the swerve drive
         * @param odometryUpdateFrequency The frequency to run the odometry loop. If
         *                                unspecified or set to 0 Hz, this is 250 Hz on
         *                                CAN FD, and 100 Hz on CAN 2.0.
         * @param modules                 Constants for each specific module
         */
        public TunerSwerveDrivetrain(
            SwerveDrivetrainConstants drivetrainConstants,
            double odometryUpdateFrequency,
            SwerveModuleConstants<?, ?, ?>... modules
        ) {
            super(
                TalonFX::new, TalonFX::new, CANcoder::new,
                drivetrainConstants, odometryUpdateFrequency, modules
            );
        }

        /**
         * Constructs a CTRE SwerveDrivetrain using the specified constants.
         * <p>
         * This constructs the underlying hardware devices, so users should not construct
         * the devices themselves. If they need the devices, they can access them through
         * getters in the classes.
         *
         * @param drivetrainConstants       Drivetrain-wide constants for the swerve drive
         * @param odometryUpdateFrequency   The frequency to run the odometry loop. If
         *                                  unspecified or set to 0 Hz, this is 250 Hz on
         *                                  CAN FD, and 100 Hz on CAN 2.0.
         * @param odometryStandardDeviation The standard deviation for odometry calculation
         *                                  in the form [x, y, theta]ᵀ, with units in meters
         *                                  and radians
         * @param visionStandardDeviation   The standard deviation for vision calculation
         *                                  in the form [x, y, theta]ᵀ, with units in meters
         *                                  and radians
         * @param modules                   Constants for each specific module
         */
        public TunerSwerveDrivetrain(
            SwerveDrivetrainConstants drivetrainConstants,
            double odometryUpdateFrequency,
            Matrix<N3, N1> odometryStandardDeviation,
            Matrix<N3, N1> visionStandardDeviation,
            SwerveModuleConstants<?, ?, ?>... modules
        ) {
            super(
                TalonFX::new, TalonFX::new, CANcoder::new,
                drivetrainConstants, odometryUpdateFrequency,
                odometryStandardDeviation, visionStandardDeviation, modules
            );
        }        
    }
}
